version: '3.8'

services:
  # PostgreSQL database
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tradingapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis for caching
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Database migration service
  migration:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tradingapp
    volumes:
      - ./backend:/app
    command: python run_migrations.py
    
  # FastAPI backend
  backend:
    build: ./backend
    depends_on:
      migration:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tradingapp
      - REDIS_URL=redis://redis:6379/0
      - ALPHA_VANTAGE_API_KEY=QRL7874F7OJAGJHY
    volumes:
      - ./backend:/app
      - backend_static:/app/app/static
    ports:
      - "8000:8000"
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  # React frontend
  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    ports:
      - "3000:3000"

  # Database initialization service
  init-db:
    build: ./backend
    depends_on:
      migration:
        condition: service_completed_successfully
      backend:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tradingapp
      - REDIS_URL=redis://redis:6379/0
      - ALPHA_VANTAGE_API_KEY=QRL7874F7OJAGJHY
    volumes:
      - ./backend:/app
      - backend_static:/app/app/static
    command: >
      sh -c "python -m app.init_db"

volumes:
  postgres_data:
  redis_data:
  backend_static: